export const AuthActionTypes = {
    USER_LOADED: 'USER_LOADED',
    USER_LOADING: 'USER_LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
};

export const CarActionTypes = {
    CARS_LOADING: 'CARS_LOADING',
    CARS_LOADED: 'CARS_LOADED',
    CARS_FAIL: 'CARS_FAIL',
    MANUFACTURERS_LOADING: 'MANUFACTURERS_LOADING',
    MANUFACTURERS_LOADED: 'MANUFACTURERS_LOADED',
    MANUFACTURERS_FAIL: 'MANUFACTURERS_FAIL',
    SUPPLIERS_LOADING: 'SUPPLIERS_LOADING',
    SUPPLIERS_LOADED: 'SUPPLIERS_LOADED',
    SUPPLIERS_FAIL: 'SUPPLIERS_FAIL',
};
