export const AuthActionTypes = {
    USER_LOADED: 'USER_LOADED',
    USER_LOADING: 'USER_LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
};
